B2c2AdapterService:
    
    RestUrl:
        settings-key: B2C2AdapterService-RestUrl

    WebSocketUrl:
        settings-key: B2C2AdapterService-WebSocketUrl

    AuthorizationToken:
        settings-key: B2C2AdapterService-AuthorizationToken

    InstrumentLevels:
        settings-key: B2C2AdapterService-InstrumentLevels
        types: 
            - JsonArray

    RfqOrderBooksSleepInterval:
        settings-key: B2C2AdapterService-RfqOrderBooksSleepInterval

    Db:
        LogsConnString:
            settings-key: B2C2AdapterService-LogsConnectionString
            types:
                - AzureTableStorage
                - Logs

    RabbitMq:
        OrderBooks:
            Enabled:
                settings-key: B2C2AdapterService-OrderBooksEnabled
            ConnectionString:
                settings-key: B2C2AdapterService-OrderBooksConnectionString
                types:
                    - RabbitMq
            ExchangeName:
                settings-key: B2C2AdapterService-OrderBooksExchangeName
        TickPrices:
            Enabled:
                settings-key: B2C2AdapterService-TickPricesEnabled
            ConnectionString:
                settings-key: B2C2AdapterService-TickPricesConnectionString
                types:
                    - RabbitMq 
            ExchangeName:
                settings-key: B2C2AdapterService-TickPricesExchangeName
        OrderBooksRfq:
            Enabled:
                settings-key: B2C2AdapterService-OrderBooksRfqEnabled
            ConnectionString:
                settings-key: B2C2AdapterService-OrderBooksRfqConnectionString
                types:
                    - RabbitMq
            ExchangeName:
                settings-key: B2C2AdapterService-OrderBooksRfqExchangeName
        TickPricesRfq:
            Enabled:
                settings-key: B2C2AdapterService-TickPricesRfqEnabled
            ConnectionString:
                settings-key: B2C2AdapterService-TickPricesRfqConnectionString
                types:
                    - RabbitMq 
            ExchangeName:
                settings-key: B2C2AdapterService-TickPricesRfqExchangeName

SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName:
            settings-key: SlackQueueName

MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl

